version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: eshop_redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.7
    container_name: eshop_queue
    ports:
      - "5672:5672"
  api:
    container_name: eshop_web
    build: ./
    ports:
      - "8088:3000"
    depends_on:
      - redis
      - rabbitmq
    links:
      - redis
      - rabbitmq
    volumes:
      - ./:/home/app
    command: [ "npm", "start" ]